name: devconsole
region: nyc

# Frontend - Static Site (React App)
static_sites:
  - name: devconsole-frontend
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: dist
    environment_slug: node-js
    envs:
      - key: VITE_API_URL
        scope: RUN_TIME
        value: ${devconsole-api.PUBLIC_URL}
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET
    routes:
      - path: /
    catchall_document: index.html

# Backend API - Web Service
services:
  - name: devconsole-api
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${devconsole-db.DATABASE_URL}
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "8080"
    routes:
      - path: /api

# Database - PostgreSQL
databases:
  - name: devconsole-db
    engine: PG
    production: true
    version: "16"
